### ISSUE TITLE
Submodule 'mbedtls' Not Pulling In

### ISSUE THREAD

**Issue by loganbenda** [FreeRTOS/corePKCS11#164]
I can't seem to get the submodule under "source/dependency/3rdparty/mbedtls" to pull in when doing the following under a custom embedded project: 

git submodule add https://github.com/FreeRTOS/corePKCS11.git ec_lib/standard/corePKCS11/corePKCS11
git submodule update --init --recursive
git submodule update --recursive --remote

[submodule "source/dependency/3rdparty/mbedtls"]
	path = source/dependency/3rdparty/mbedtls
	url = https://github.com/ARMmbed/mbedtls.git
	branch = v2.28.0
	update = none

I see that the 'update' tag is set to 'none'. When cloning and updating the aws-iot-device-sdk-embedded-c the repository pulls in fine. Am I missing something when pulling the FreeRTOS cores individually?

Thanks!

**Comment by paulbartell** [comment]
Hello @loganbenda. Welcome to the community. 

The `update=none` option is set that way intentionally. The mbedtls submodule exists in this repository due to limitations in our CBMC test infrastructure. We have a task on our backlog to address limitation that and remove the submodule altogether.

corePKCS#11 can be used with a variety of mbedtls versions. We test it with versions 2.28.x and 3.x. During integration testing, we fetch mbedtls versions 2.x and 3.x using cmake's FetchContent feature in [tools/mbedtls.cmake](https://github.com/FreeRTOS/corePKCS11/blob/main/tools/mbedtls.cmake), which may be a useful reference.

Keep in mind that corePKCS#11 is just meant as a prototyping and validation tool to stand in for a secure element. In most cases it is much simpler to store keys in encrypted flash (if not using a secure element) or call the relevant functions in your secure element's SDK directly.

I will close this issue, but do feel free to reopen it if you have further related questions.
